# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = '.pio/build/ESP32-c3-devkit/firmware.bin'
elf = '.pio/build/ESP32-c3-devkit/firmware.elf'
